apiVersion: v1
kind: Service
metadata:
  name: expense-backend
  namespace: expense-app
spec:
  selector:
    app: expense-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
