apiVersion: v1
kind: Service
metadata:
  name: expense-frontend
  namespace: expense-app
spec:
  type: LoadBalancer
  selector:
    app: expense-frontend
  ports:
    - port: 80
      targetPort: 3000
